//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOAudit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LiveConnectDbEntities : DbContext
    {
        public LiveConnectDbEntities()
            : base("name=LiveConnectDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WOAuditEntry> WOAuditEntries { get; set; }
        public virtual DbSet<WOAuditWONumber> WOAuditWONumbers { get; set; }
        public virtual DbSet<WOAuditWOPNumber> WOAuditWOPNumbers { get; set; }
        public virtual DbSet<WOAuditDump> WOAuditDumps { get; set; }
        public virtual DbSet<WOAuditDumpLive> WOAuditDumpLives { get; set; }
    
        public virtual ObjectResult<THAS_CONNECT_GetWorksOrdersForAudit_Result> THAS_CONNECT_GetWorksOrdersForAudit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THAS_CONNECT_GetWorksOrdersForAudit_Result>("THAS_CONNECT_GetWorksOrdersForAudit");
        }
    
        public virtual ObjectResult<THAS_CONNECT_GetWorksOrdersForAuditLive_Result> THAS_CONNECT_GetWorksOrdersForAuditLive()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THAS_CONNECT_GetWorksOrdersForAuditLive_Result>("THAS_CONNECT_GetWorksOrdersForAuditLive");
        }
    }
}
