//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOAudit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ReportConnectDbEntities : DbContext
    {
        public ReportConnectDbEntities()
            : base("name=ReportConnectDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WOAuditChanx> WOAuditChanges { get; set; }
        public virtual DbSet<WOAuditDump> WOAuditDumps { get; set; }
        public virtual DbSet<WOAuditDumpLive> WOAuditDumpLives { get; set; }
        public virtual DbSet<WOAuditEntry> WOAuditEntries { get; set; }
        public virtual DbSet<WOAuditWONumber> WOAuditWONumbers { get; set; }
        public virtual DbSet<WOAuditWOPNumber> WOAuditWOPNumbers { get; set; }
        public virtual DbSet<WOPartAuditChanx> WOPartAuditChanges { get; set; }
    
        public virtual int THAS_CONNECT_CopyWorksOrderChanges()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THAS_CONNECT_CopyWorksOrderChanges");
        }
    
        public virtual ObjectResult<THAS_CONNECT_GetWorksOrdersForAudit_Result> THAS_CONNECT_GetWorksOrdersForAudit()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THAS_CONNECT_GetWorksOrdersForAudit_Result>("THAS_CONNECT_GetWorksOrdersForAudit");
        }
    
        public virtual ObjectResult<THAS_CONNECT_GetWorksOrdersForAuditLive_Result> THAS_CONNECT_GetWorksOrdersForAuditLive()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THAS_CONNECT_GetWorksOrdersForAuditLive_Result>("THAS_CONNECT_GetWorksOrdersForAuditLive");
        }
    
        public virtual int THAS_CONNECT_CopyWorksOrderPartChanges()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THAS_CONNECT_CopyWorksOrderPartChanges");
        }
    
        public virtual ObjectResult<THAS_CONNECT_WorksOrderAuditAdditions_Result> THAS_CONNECT_WorksOrderAuditAdditions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THAS_CONNECT_WorksOrderAuditAdditions_Result>("THAS_CONNECT_WorksOrderAuditAdditions");
        }
    
        public virtual ObjectResult<THAS_CONNECT_WorksOrderAuditDeletions_Result> THAS_CONNECT_WorksOrderAuditDeletions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THAS_CONNECT_WorksOrderAuditDeletions_Result>("THAS_CONNECT_WorksOrderAuditDeletions");
        }
    
        public virtual ObjectResult<THAS_CONNECT_WorksOrderPartAuditAdditions_Result> THAS_CONNECT_WorksOrderPartAuditAdditions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THAS_CONNECT_WorksOrderPartAuditAdditions_Result>("THAS_CONNECT_WorksOrderPartAuditAdditions");
        }
    }
}
