//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOAudit
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOAuditWONumber
    {
        public long WO_AuditID { get; set; }
        public int WOTID { get; set; }
    }
}
