//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOAudit
{
    using System;
    using System.Collections.Generic;
    
    public partial class WOAuditEntry
    {
        public long WOAuditEntry_ID { get; set; }
        public string Type { get; set; }
        public int WOPart { get; set; }
        public int WOTID { get; set; }
        public string WorksOrderNumber { get; set; }
        public string WOLevel { get; set; }
        public string FieldName { get; set; }
        public string ChangedFrom { get; set; }
        public string ChangedTo { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    }
}
